#!/bin/sh

cachedir="${XDG_CACHE_HOME:-"$HOME/.cache"}"
cache="$cachedir/swenu-run"

[ ! -e "$cachedir" ] && mkdir -p "$cachedir"

if swenu-exes "$cache"; then
	swenu-exes | sort -u | tee $cache
else
	cat $cache
fi
